version: '3'

services:
  mi-api:
    image: node:14
    volumes:
      - ./mi-api:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: npm start
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodb_data:
